# Generated by Django 2.0 on 2018-01-04 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
                ('date_joined', models.DateTimeField(default='date_pubished')),
                ('last_login', models.DateTimeField()),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-Mail Adresse')),
                ('is_superuser', models.BooleanField(default='False')),
                ('is_active', models.BooleanField(default='True')),
                ('is_admin', models.BooleanField(default='False')),
                ('display_email', models.BooleanField(default='False')),
                ('pgppublic', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BetaFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, null=True)),
                ('verification', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BetaGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Betajob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('Jobstatus', models.CharField(choices=[('1', 'Wartend'), ('2', 'In Arbeit'), ('3', 'Pausiert'), ('4', 'Abgebrochen'), ('5', 'Korrigiert'), ('6', 'Abgenommen'), ('7', 'Abgelehnt')], default='Wartend', max_length=10)),
                ('stopReason', models.CharField(max_length=255, null=True)),
                ('endDate', models.DateField(null=True)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BetaLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colloguial', models.BooleanField(default=False)),
                ('formal', models.BooleanField(default=False)),
                ('antiquated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Betareader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BetaTextsort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betareader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Betareader')),
            ],
        ),
        migrations.CreateModel(
            name='BetaTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betareader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Betareader')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000)),
                ('commReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reveiver', to=settings.AUTH_USER_MODEL)),
                ('commSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betareader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Betareader')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='user_directory_path')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('DOCX', 'docx'), ('DOC', 'doc'), ('ODT', 'odt'), ('PDF', 'pdf')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=30)),
                ('factdefinition', models.TextField()),
                ('factparent', models.PositiveIntegerField()),
                ('propose_date', models.DateTimeField()),
                ('status', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(max_length=25)),
                ('focusdefinition', models.TextField()),
                ('focusparent', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=25)),
                ('genredefinition', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('language_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageDialect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialect', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('leveldefinition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=10)),
                ('prioritydefinition', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=240)),
                ('genre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='betaluchs.Genre')),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Textsort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textsort', models.CharField(max_length=25)),
                ('sortdefinition', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=30)),
                ('themedefinition', models.CharField(max_length=500)),
                ('themeparent', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='textsort',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='betaluchs.Textsort'),
        ),
        migrations.AddField(
            model_name='project',
            name='themes',
            field=models.ManyToManyField(to='betaluchs.Theme'),
        ),
        migrations.AddField(
            model_name='genre',
            name='textsortID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Textsort'),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Project'),
        ),
        migrations.AddField(
            model_name='communication',
            name='cooperation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Cooperation'),
        ),
        migrations.AddField(
            model_name='betatheme',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betaluchs.Priority'),
        ),
        migrations.AddField(
            model_name='betatheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Theme'),
        ),
        migrations.AddField(
            model_name='betatextsort',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betaluchs.Priority'),
        ),
        migrations.AddField(
            model_name='betatextsort',
            name='textsort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Textsort'),
        ),
        migrations.AddField(
            model_name='betareader',
            name='factKnowlege',
            field=models.ManyToManyField(through='betaluchs.BetaFacts', to='betaluchs.Facts'),
        ),
        migrations.AddField(
            model_name='betareader',
            name='genrePriority',
            field=models.ManyToManyField(through='betaluchs.BetaGenre', to='betaluchs.Genre'),
        ),
        migrations.AddField(
            model_name='betareader',
            name='languageKnowlege',
            field=models.ManyToManyField(through='betaluchs.BetaLanguage', to='betaluchs.Language'),
        ),
        migrations.AddField(
            model_name='betareader',
            name='projects',
            field=models.ManyToManyField(through='betaluchs.Cooperation', to='betaluchs.Project'),
        ),
        migrations.AddField(
            model_name='betareader',
            name='textsortPriotiry',
            field=models.ManyToManyField(through='betaluchs.BetaTextsort', to='betaluchs.Textsort'),
        ),
        migrations.AddField(
            model_name='betareader',
            name='themePriority',
            field=models.ManyToManyField(through='betaluchs.BetaTheme', to='betaluchs.Theme'),
        ),
        migrations.AddField(
            model_name='betareader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='betalanguage',
            name='betareader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Betareader'),
        ),
        migrations.AddField(
            model_name='betalanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Language'),
        ),
        migrations.AddField(
            model_name='betalanguage',
            name='levelid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='betaluchs.Level'),
        ),
        migrations.AddField(
            model_name='betajob',
            name='betareader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Betareader'),
        ),
        migrations.AddField(
            model_name='betajob',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Document'),
        ),
        migrations.AddField(
            model_name='betagenre',
            name='betareader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Betareader'),
        ),
        migrations.AddField(
            model_name='betagenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Genre'),
        ),
        migrations.AddField(
            model_name='betagenre',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betaluchs.Priority'),
        ),
        migrations.AddField(
            model_name='betafacts',
            name='betareader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Betareader'),
        ),
        migrations.AddField(
            model_name='betafacts',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betaluchs.Facts'),
        ),
        migrations.AddField(
            model_name='betafacts',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='betaluchs.Level'),
        ),
    ]
