# Generated by Django 2.0 on 2018-01-04 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betaluchs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=30)),
                ('factdefinition', models.TextField()),
                ('factparent', models.PositiveIntegerField()),
                ('propose_date', models.DateTimeField()),
                ('status', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(max_length=25)),
                ('focusdefinition', models.TextField()),
                ('focusparent', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=25)),
                ('genredefinition', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('language_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('leveldefinition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Textsort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textsort', models.CharField(max_length=25)),
                ('sortdefinition', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=30)),
                ('themedefinition', models.CharField(max_length=500)),
                ('themeparent', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=240),
        ),
        migrations.AddField(
            model_name='genre',
            name='textsortID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betaluchs.Textsort'),
        ),
        migrations.AddField(
            model_name='project',
            name='genre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='betaluchs.Genre'),
        ),
        migrations.AddField(
            model_name='project',
            name='textsort',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='betaluchs.Textsort'),
        ),
        migrations.AddField(
            model_name='project',
            name='themes',
            field=models.ManyToManyField(to='betaluchs.Theme'),
        ),
    ]
